config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: 'muscles#index'

  get '/muscles/startmuscle',  to: 'muscles#start_muscle'

  get '/muscles/searchmuscle',  to: 'muscles#search_muscle'
  resources :muscles, only: [:index,:new,:show,:create,:destroy] do
    collection do
      get 'search'
    end
  end


  resources :muscles
  resources :muscles do
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :muscle

  validates :text,     presence: true
end

app/models/difficult.rb
class Difficult < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '簡単' },
    { id: 3, name: 'やや簡単' },
    { id: 4, name: '普通' },
    { id: 5, name: 'やや難しい' },
    { id: 6, name: '難しい' }
  ]

  include ActiveHash::Associations
  has_many :muscles
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :muscle
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :part
  belongs_to_active_hash :difficult

  with_options presence: true do
    validates :image
    validates :title
    validates :explain
    validates :daytime
  end

  with_options numericality: { other_than: 1, message: 'Select' } do
    validates :part_id
    validates :difficult_id
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def start_time
    self.daytime
  end
end

app/models/part.rb
class Part < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '肩' },
    { id: 3, name: '腕' },
    { id: 4, name: '背筋' },
    { id: 5, name: '腹筋' },
    { id: 6, name: '足' }
  ]

  include ActiveHash::Associations
  has_many :muscles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :muscles, dependent: :destroy
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_muscles, through: :favorites, source: :muscle

  validates :nickname, presence: true
  validates :profile , presence: true
  validates :goal    , presence: true

  has_one_attached :avatar, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :goal, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile, :goal, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to muscle_path(@comment.muscle)
    else
      @muscle = @comment.muscle
      @comments = @muscle.comments
      render "muscles/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, muscle_id: params[:muscle_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @muscle = Muscle.find(params[:muscle_id])
    @favorite = current_user.favorites.build(muscle_id: params[:muscle_id])
    @favorite.save
    redirect_to muscles_path
  end

  def destroy
    @muscle = Muscle.find(params[:muscle_id])
    @favorite = Favorite.find_by(muscle_id: params[:muscle_id], user_id: current_user.id)
    @favorite.destroy
    redirect_to muscles_path
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_muscle, only: [:show, :edit, :update]
  before_action :create_searching_object,only: [:index,:search_muscle]

  def index
    @user = current_user
    @muscles = Muscle.includes(:favorite_users).sort {|a,b| b.favorite_users.size <=> a.favorite_users.size}
  end

  def new
    @muscle = Muscle.new
  end

  def create
    @muscle = Muscle.new(muscle_params)
    if @muscle.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @muscle.comments.includes(:user)
  end

  def edit
    unless @muscle.user.id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    if @muscle.update(muscle_params)
      redirect_to muscle_path
    else
      render :edit
    end
  end

  def destroy
    muscle =Muscle.find(params[:id])
    muscle.destroy
    redirect_to root_path
  end


  def search_muscle
    @results = @p.result
  end

  def start_muscle
  end

  private
  def muscle_params
    params.require(:muscle).permit(:image, :title, :explain, :part_id, :difficult_id, :daytime).merge(user_id: current_user.id)
  end

  def set_muscle
    @muscle = Muscle.find(params[:id])
  end

  def create_searching_object
    @p = Muscle.ransack(params[:q]) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @muscles = @user.muscles
    @favorite_muscles = @user.favorite_muscles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
  <% if user_signed_in? %>
    <% if muscle.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><%=link_to image_tag("good.png", size: '30x30' ,class: :good), muscle_favorites_path(muscle.id), method: :delete %></p>
        <span>いいね数: </span><%= muscle.favorites.count %>
    <% else %>
        <p><%=link_to image_tag("nogood.png", size: '30x30' ,class: :good), muscle_favorites_path(muscle.id), method: :post %></p>
        <span>いいね数: </span><%= muscle.favorites.count %>
    <% end %>
  <% else %>
    <p><span>いいね数: </span><%= muscle.favorites.count %></p>
  <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('.likes_buttons_<%= @muscle.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {muscle: @muscle}) %>");

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('.likes_buttons_<%= @muscle.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {muscle: @muscle}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>THE FIRST MUSCLE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <div class="greeting">
                <%= "こんにちは、" %>
                <%= link_to current_user.nickname, "/users/#{current_user.id}", class: :greeting__link%>
                <%= "さん" %>
              </div>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">このアプリを作った人は、サイクリングが大好きです。コピーしないでね☆</p>
    </footer>
  </body>
</html>

app/views/muscles/_form.html.erb
<%# 部分テンプレート（トレーニング内容の編集用）%>
<%= form_with model:muscle, local: true do |f|%>

  <%= render partial: 'shared/error_messages', locals: { model: f.object } %>

  <div class="field">
    <%= f.label :image, "トレーニング画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title, "トレーニング名" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :explain, "トレーニング内容" %><br />
    <%= f.text_area :explain, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :part_id, "部位" %><br />
    <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>

  <div class="field">
    <%= f.label :difficult_id, "難易度" %><br />
    <%= f.collection_select(:difficult_id, Difficult.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>

  <div class="field">
    <%= f.label :daytime, "日にち" %><br />
    <%= f.datetime_select :daytime %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/muscles/_muscle.html.erb
<%# 部分テンプレート（各トレーニング内容の表示）%>
<div class="card">
  <%= link_to image_tag(muscle.image, class: :card__img ), muscle_path(muscle.id), method: :get %>
  <div class="card__body">
    <%= link_to muscle.title, muscle_path(muscle.id), method: :get , class: :card__title%>
    <p class="card__summary">
      <%= "部位・・・#{muscle.part.name}" %>
    </p>
    <p class="card__summary">
      <%= "難易度・・・#{muscle.difficult.name}" %>
    </p>
    <%= link_to "by #{muscle.user.nickname}" , "/users/#{muscle.user.id}", class: :card__user %>
  </div>
  <div id="likes_buttons_<%= muscle.id %>">
    <%= render partial: 'favorites/favorite', locals: { muscle: muscle} %>
  </div>
</div>

app/views/muscles/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "muscles/form", locals: { muscle: @muscle } %>
    </div>
  </div>
</div>

app/views/muscles/index.html.erb
<%# トップ画面にランダムで言葉を表示させる%>
<% random_number = SecureRandom.random_number(6) %>
<% if random_number == 0 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>やあ、みんな!</strong> 今日も1日頑張ろう！！
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif random_number == 1 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>お疲れ様!</strong> 今日は難易度を一つ上げてみては？？(bﾟv`*)
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif random_number == 2 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>占いします！！！</strong> 大吉！！！！！
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif random_number == 3 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>今日の晩御飯は・・・</strong> とりささみ！にしましょう🐔
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif random_number == 4 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>今日のおすすめの部位は</strong> 肩です！！
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif random_number == 5 %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>実は・・・</strong> 水瀬いのりさんのファンです。
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<main class="main">
  <div class="inner">
    <div class="inner-main">
      <div class="new-muscle">
        <%= "初めての人は" %>
        <%= link_to "こちらをクリック", muscles_startmuscle_path, class: :click_link %>
      </div>
      <%# BMIについて%>
      <div class="bmi">
        <%= image_tag 'boy.png' ,class: "boy" %>
        <h3 class="bmi-title">📋 BMIを調べてみよう！</h3>
        <h6>BMIとは体重と身長から算出される肥満度のことです。</h6>

        <table border="1">
          <tr>
            <th>BMI値</th>
            <th>判定</th>
          </tr>
          <tr>
            <td>18.5未満</td>
            <td>痩せ型</td>
          </tr>
          <tr>
            <td>18.5~25未満</td>
            <td>普通体型</td>
          </tr>
          <tr>
            <td>25~30未満</td>
            <td>肥満(1度)</td>
          </tr>
          <tr>
            <td>30~35未満</td>
            <td>肥満(2度)</td>
          </tr>
          <tr>
            <td>35~40未満</td>
            <td>肥満(3度)</td>
          </tr>
          <tr>
            <td>40以上</td>
            <td>肥満(4度)</td>
          </tr>
        </table>
        <h6>※データは保存されません。</h6>
        <h6>安心してご利用ください。</h6>
        <div class="container">
          <div class="row">
            <section class="col-sm-6 col-md-4 pt-4">
              <div class="form-group">
                <label for="height">身長 (cm)</label>
                <input id="height-input" type="text" class="form-control" placeholder="例) 165">
              </div>
              <div class="form-group">
                <label for="weight">体重 (kg)</label>
                <input id="weight-input" type="text" class="form-control" placeholder="例) 60">
              </div>
                <input id="button-submit" type="submit" class="btn btn-primary btn-large" value="計測開始">
            </section>
            <section class="col-sm-6 col-md-4 pt-4">
              <div class="card">
                <div class="card-header">
                  あなたのBMI
                </div>
                <div class="card-body">
                  <div id="bmi-output" class="display-4"></div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="greeting goal">
          <%= "あなたの目標は・・・" %>
          <%= link_to current_user.goal, "/users/#{current_user.id}", class: :greeting__link%>
        </div>
      <% end %>
      <%# もし何も投稿がなかったら表示させる%>

      <%# 検索欄 %>
      <%= search_form_for @p, url: muscles_searchmuscle_path do |f| %>
        <p class="category-title">🔍 カテゴリー検索</p>
        <div class="search-header">
          <%= f.label '部位'%>
          <%= f.collection_select :part_id_eq,Part.all,:id,:name %>
          <%= f.label '難易度'%>
          <%= f.collection_select :difficult_id_eq,Difficult.all,:id,:name %>
          <%= f.submit '検索' %>
        </div>
      <% end %>

      <%# 投稿したものの一覧表示 %>
      <div class="card__wrapper">
        <%= render partial:"muscle", collection: @muscles %>
      </div>
    </div>
  </div>
</main>

<%= link_to(new_muscle_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'dumbbell.png' , size: '200x70' ,class: "purchase-btn-icon" %>
<% end %>

<%= javascript_pack_tag 'test' %>
<%= javascript_pack_tag 'bmi' %>

app/views/muscles/new.html.erb
<%# 部分テンプレート（新規トレーニング作成画面）%>
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">💪新規トレーニング投稿💪</h2>
        <%= render partial: "muscles/form",locals: { muscle: @muscle } %>
    </div>
  </div>
</div>

app/views/muscles/search_muscle.html.erb
<main class="main">
  <div class="inner">
    <div class="inner-main">
      <h1 class="search-title">💪検索結果💪</h1>

      <%# もし、検索結果が0でなければ表示させる。それ以外なら、メッセージを表示　%>
      <% if @results.length !=0 %>
        <div class="inner">
          <div class="card__wrapper">
            <%= render partial:"muscle", collection: @results %>
          </div>
        </div>
      <% else %>
        <h4>🙇‍♂️申し訳ございません！該当するトレーニングが見つかりませんでした！🙇‍♂️</h4>
      <% end %>
      <br>
      <%= link_to 'トップページへ戻る', root_path ,class: :top_page %>
    </div>
  </div>
</div>

app/views/muscles/show.html.erb
<main class="main">
  <div class="inner">
    <div class="inner-main">
      <div class="prototype__wrapper">
        <div class="prototype__image">
          <%= image_tag @muscle.image %>
        </div>
        <p class="prototype__hedding">
          <%= @muscle.title %>
        </p>
        <%= link_to "by #{@muscle.user.nickname}", "/users/#{@muscle.user.id}", class: :prototype__user %>
        <div class="prototype__body">
          <div class="prototype__detail">
            <p class="detail__title">トレーニング内容</p>
            <p class="detail__message">
              <%= @muscle.explain %>
            </p>
          </div>
          <div class="prototype__detail">
            <p class="detail__title">難易度</p>
            <p class="detail__message">
              <%= @muscle.difficult.name %>
            </p>
          </div>
        </div>
        <% if user_signed_in? && current_user.id == @muscle.user_id %>
          <div class="prototype__manage">
            <%= link_to "編集する", edit_muscle_path(@muscle.id), method: :get , class: :prototype__btn %>
            <%= link_to "削除する", muscle_path(@muscle.id), method: :delete , class: :prototype__btn %>
          </div>
        <% end %>

        <div class="prototype__comments">
          <% if user_signed_in? %>
            <%= form_with model:[@muscle,@comment], local: true do |f|%>
              <div class="field">
                <%= f.label :text, "コメント" %><br />
                <%= f.text_field :text %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %>
          <ul class="comments_lists">
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= comment.text %>
                <%= link_to "(#{comment.user.nickname})", "/users/#{comment.user.id}", class: :comment_user %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/muscles/start_muscle.html.erb
<main class="main">
  <div class="inner">
    <div class="inner-main">
      <div class="start-comments">
        <h2 class="howto-title">みなさんこんにちは!!</h2>
        <p>このアプリは筋トレを始めるきっかけが与えられないかと思い作成しました！
        <p>様々な筋トレを共有することで、皆で筋トレを続けて行けたら良いなと思っています😆
      </div>
      <div class="how-to">
        <h2 class="howto-title">HOW-TO</h2>
        <p>　まず、主な使い方として２パターンあります。</p>
        <p>　１つは、自分が行いたいトレーニングをカテゴリーから探してやってみること。</p>
        <a href="https://gyazo.com/2933a162a2fc20dcf63d99bcfffa39df"><img src="https://i.gyazo.com/2933a162a2fc20dcf63d99bcfffa39df.png" alt="Image from Gyazo" width="510"/></a>
        <p>この検索の並びはいいね順になっているので、上からやるのがおすすめだったりします。</p>
        <p>　</p>
        <p>　もう１つは自分が考えたおすすめのトレーニングがあったら投稿することです！</p>
        <p>まず右下にあるこの「投稿する」ボタンを押します。</p>
        <a href="https://gyazo.com/8662c5577559873b12ac324939a21855"><img src="https://i.gyazo.com/8662c5577559873b12ac324939a21855.png" alt="Image from Gyazo" width="222"/></a>
        <p>次に新規投稿ページにて必要項目を入れていきます。下記の画像は一例です。</p>
        <a href="https://gyazo.com/fe720180c6ac1ef04d01eff67f64d9c2"><img src="https://i.gyazo.com/fe720180c6ac1ef04d01eff67f64d9c2.png" alt="Image from Gyazo" width="915"/></a>
        <p>※難易度は、初心者がどのように感じるかのイメージで判断してみてください。</p>
        <p>※日にちは、その日付がMYカレンダーに反映されます。</p>
        <p>「投稿日」や「トレーニング予定日」などお好きに入れてください。</p>
        <div class="start-muscle">
          <%= link_to "早速、登録してみる！", new_user_registration_path %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading cal-head">
    <%= link_to t('simple_calendar.previous', default: '＜＝'), calendar.url_for_previous_view %>
    <span class="calendar-title year-month"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '＝＞'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading cal-head">
    <%= link_to t('simple_calendar.previous', default: '＜＝'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: '＝＞'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="inner-main">
      <div class="user__wrapper">
        <h2 class="page-heading">
          <%= "#{@user.nickname}さんの詳細情報"%>
        </h2>
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar.variant(resize: '180x180') %>
        <% end %>
        <table class="table">
          <tbody>
            <tr>
              <th class="table__col1">名前</th>
              <td class="table__col2"><%= @user.nickname %></td>
            </tr>
            <tr>
              <th class="table__col1">プロフィール</th>
              <td class="table__col2"><%= @user.profile %></td>
            </tr>
            <tr>
              <th class="table__col1">目標</th>
              <td class="table__col2"><%= @user.goal %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to "ユーザー情報を編集", edit_user_registration_path%>

        <h1 class="training-title">MYカレンダー</h1>
        <div class="calendar">
          <%= week_calendar events: @muscles do |date, muscles| %>
            <%= date.day %>
            <% muscles.each do |muscle| %>
              <div>
                <%= link_to muscle.title, muscle %>
              </div>
            <% end %>
          <% end %>
        </div>


        <h2 class="page-heading">
          <%= "#{@user.nickname}さんのトレーニング"%>
        </h2>

        <div class="user__card">
          <%= render partial: "muscles/muscle", collection: @muscles %>
        </div>

        <div class="favorite-space">
          <h2>いいねしたトレーニング</h2>
          <% @favorite_muscles.each do |muscle| %>
            <hr>
            <%=link_to muscle.title , muscle_path(muscle.id) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>